run:
  timeout: 5m
  concurrency: 4
  fast: true
  tests: true

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - revive
    - unused
    - unparam
    - gofmt 
    - goimports
  disable:
    - dupl
    - gocritic
    - funlen
    - goconst
    - lll

linters-setting:
  govent:
    check-shadowing: truegocyclo
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/nashabanov/ueba-event-generator

formatters:
  enable:
    - goimports
    - golines

issues:
  max-sama-issue: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - gomnd
        - errcheck
        - revive
    - path: cmd/
      linters:
        - gochecknoinits
  exclude:
    - 'should have a package comment'
    - 'line is \d+ characters'

output:
  formats:
    - format: colored-line-number

