// Package metrics exports Prometheus metrics for the Pulsar load generator
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	GeneratedEvents = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_events_generated_total",
		Help: "Total number of events generated by the generator",
	})
	SentEvents = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_events_sent_total",
		Help: "Total number of events successfullly delivered to destination",
	})
	FailedEvents = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_events_failed_total",
		Help: "Total number of events that failed to be sent due to errors",
	})
	DroppedEvents = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_events_dropped_total",
		Help: "Total number of events dropped to internal resourse constraints",
	})

	ActiveWorkers = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "pulsar_workers_active",
		Help: "Current number of active worker goroutines",
	})
	QueuedJobs = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "pulsar_jobs_queued",
		Help: "Current number of jobs waiting in queue to be processed by workers",
	})
	CompletedJobs = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_jobs_completed_total",
		Help: "Total number of jobs successfully processed by the worker pool",
	})
	RejectedJobs = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsar_jobs_rejected_total",
		Help: "Total number of jobs rejected because the job queue was at capacity",
	})
)
